# Generated by Django 4.2 on 2023-04-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customusermodel_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
